export interface SEOKeywordDetail {
  phrase: string;
  category: 'purchase_delivery' | 'dosage_usage' | 'prices_pharmacies' | 'side_effects' | 'general_medical';
  categoryAr: string;
  estimatedVolume: number;
}

export const SEO_CAMPAIGN_KEYWORDS: SEOKeywordDetail[] = [
  // 1. Purchase & Delivery Keywords
  { phrase: 'حبوب سايتوتك الاصلية', category: 'purchase_delivery', categoryAr: 'الشراء والأصالة', estimatedVolume: 920 },
  { phrase: 'حبوب اجهاض للبيع', category: 'purchase_delivery', categoryAr: 'التوصيل والشراء', estimatedVolume: 880 },
  { phrase: 'شراء حبوب سايتوتك', category: 'purchase_delivery', categoryAr: 'الشراء والأصالة', estimatedVolume: 950 },
  { phrase: 'حبوب الإجهاض الأصلية', category: 'purchase_delivery', categoryAr: 'الشراء والأصالة', estimatedVolume: 900 },
  { phrase: 'شراء cytotec اون لاين', category: 'purchase_delivery', categoryAr: 'الشراء والأصالة', estimatedVolume: 780 },
  { phrase: 'cytotec للبيع', category: 'purchase_delivery', categoryAr: 'التوصيل والشراء', estimatedVolume: 850 },
  { phrase: 'abortion pills online', category: 'purchase_delivery', categoryAr: 'التوصيل والشراء', estimatedVolume: 720 },
  { phrase: 'buy cytotec safely', category: 'purchase_delivery', categoryAr: 'التوصيل والشراء', estimatedVolume: 690 },
  { phrase: 'شراء cytotec بسرعة', category: 'purchase_delivery', categoryAr: 'التوصيل والشراء', estimatedVolume: 810 },
  { phrase: 'توصيل حبوب سايتوتك', category: 'purchase_delivery', categoryAr: 'التوصيل والشراء', estimatedVolume: 890 },
  { phrase: 'cytotec الدفع عند الاستلام', category: 'purchase_delivery', categoryAr: 'التوصيل والشراء', estimatedVolume: 840 },
  { phrase: 'شراء حبوب الإجهاض بسرية', category: 'purchase_delivery', categoryAr: 'التوصيل والشراء', estimatedVolume: 930 },
  { phrase: 'شراء سايتوتك مضمون', category: 'purchase_delivery', categoryAr: 'الشراء والأصالة', estimatedVolume: 760 },
  { phrase: 'افضل موقع لشراء cytotec', category: 'purchase_delivery', categoryAr: 'الشراء والأصالة', estimatedVolume: 800 },
  { phrase: 'صيدلية اونلاين لبيع حبوب الاجهاض', category: 'purchase_delivery', categoryAr: 'الشراء والأصالة', estimatedVolume: 820 },
  { phrase: 'اماكن شراء سايتوتيك', category: 'purchase_delivery', categoryAr: 'الشراء والأصالة', estimatedVolume: 870 },
  { phrase: 'شراء حبوب الإجهاض اونلاين', category: 'purchase_delivery', categoryAr: 'الشراء والأصالة', estimatedVolume: 910 },
  { phrase: 'اماكن مضمونة لبيع حبوب الاجهاض فى السعودية', category: 'purchase_delivery', categoryAr: 'الشراء والأصالة', estimatedVolume: 880 },

  // 2. Geography & Regional Target Keywords
  { phrase: 'حبوب اجهاض في السعوديه', category: 'purchase_delivery', categoryAr: 'تغطية المملكة العربية السعودية', estimatedVolume: 990 },
  { phrase: 'حبوب سايتوتك في السعوديه', category: 'purchase_delivery', categoryAr: 'تغطية المملكة العربية السعودية', estimatedVolume: 960 },
  { phrase: 'سايتوتك السعودية', category: 'purchase_delivery', categoryAr: 'تغطية المملكة العربية السعودية', estimatedVolume: 940 },
  { phrase: 'حبوب الاجهاض السعودية', category: 'purchase_delivery', categoryAr: 'تغطية المملكة العربية السعودية', estimatedVolume: 910 },
  { phrase: 'حبوب اجهاض جدة', category: 'purchase_delivery', categoryAr: 'تغطية المملكة العربية السعودية', estimatedVolume: 820 },
  { phrase: 'حبوب سايتوتك في السعودية', category: 'purchase_delivery', categoryAr: 'تغطية المملكة العربية السعودية', estimatedVolume: 850 },
  { phrase: 'سايتوتيك السعودية', category: 'purchase_delivery', categoryAr: 'تغطية المملكة العربية السعودية', estimatedVolume: 870 },
  { phrase: 'سايتوتيك للبيع في الرياض', category: 'purchase_delivery', categoryAr: 'تغطية المملكة العربية السعودية', estimatedVolume: 930 },
  { phrase: 'سايتوتيك في الامارات', category: 'purchase_delivery', categoryAr: 'تغطية دولة الإمارات العربية المتحدة', estimatedVolume: 790 },
  { phrase: 'سايتوتيك الكويت', category: 'purchase_delivery', categoryAr: 'تغطية دولة الكويت', estimatedVolume: 810 },
  { phrase: 'سايتوتيك البحرين', category: 'purchase_delivery', categoryAr: 'تغطية مملكة البحرين', estimatedVolume: 740 },
  { phrase: 'حبوب سايتوتيك البحرين', category: 'purchase_delivery', categoryAr: 'تغطية مملكة البحرين', estimatedVolume: 720 },
  { phrase: 'cytotec جدة', category: 'purchase_delivery', categoryAr: 'تغطية المملكة العربية السعودية', estimatedVolume: 650 },
  { phrase: 'cytotec الرياض', category: 'purchase_delivery', categoryAr: 'تغطية المملكة العربية السعودية', estimatedVolume: 690 },
  { phrase: 'سايتوتيك الرياض', category: 'purchase_delivery', categoryAr: 'تغطية المملكة العربية السعودية', estimatedVolume: 820 },
  { phrase: 'سايتوتيك فى السعودية', category: 'purchase_delivery', categoryAr: 'تغطية المملكة العربية السعودية', estimatedVolume: 890 },
  { phrase: 'حبوب الاجهاض السعوديه', category: 'purchase_delivery', categoryAr: 'تغطية المملكة العربية السعودية', estimatedVolume: 850 },
  { phrase: 'حبوب سايتوتك الرياض', category: 'purchase_delivery', categoryAr: 'تغطية المملكة العربية السعودية', estimatedVolume: 910 },
  { phrase: 'حبوب اجهاض الرياض', category: 'purchase_delivery', categoryAr: 'تغطية المملكة العربية السعودية', estimatedVolume: 900 },
  { phrase: 'حبوب سايتوتك للبيع في الامارات', category: 'purchase_delivery', categoryAr: 'تغطية دولة الإمارات العربية المتحدة', estimatedVolume: 780 },
  { phrase: 'حبوب اجهاض الكويت', category: 'purchase_delivery', categoryAr: 'تغطية دولة الكويت', estimatedVolume: 820 },
  { phrase: 'حبوب سايتوتك في الكويت', category: 'purchase_delivery', categoryAr: 'تغطية دولة الكويت', estimatedVolume: 840 },
  { phrase: 'سايتوتك للبيع في الامارات', category: 'purchase_delivery', categoryAr: 'تغطية دولة الإمارات العربية المتحدة', estimatedVolume: 800 },
  { phrase: 'سايتوتك دبي', category: 'purchase_delivery', categoryAr: 'تغطية دولة الإمارات العربية المتحدة', estimatedVolume: 850 },
  { phrase: 'حبوب اجهاض في الرياض', category: 'purchase_delivery', categoryAr: 'تغطية المملكة العربية السعودية', estimatedVolume: 890 },
  { phrase: 'حبوب الاجهاض الرياض', category: 'purchase_delivery', categoryAr: 'تغطية المملكة العربية السعودية', estimatedVolume: 870 },
  { phrase: 'سايتوتك الامارات', category: 'purchase_delivery', categoryAr: 'تغطية دولة الإمارات العربية المتحدة', estimatedVolume: 810 },
  { phrase: 'حبوب اجهاض الامارات', category: 'purchase_delivery', categoryAr: 'تغطية دولة الإمارات العربية المتحدة', estimatedVolume: 830 },
  { phrase: 'سايتوتك الكويت', category: 'purchase_delivery', categoryAr: 'تغطية دولة الكويت', estimatedVolume: 860 },

  // Egypt Support Fallback Keywords (as requested)
  { phrase: 'سعر cytotec في مصر', category: 'prices_pharmacies', categoryAr: 'تغطية ومتابعة مصر', estimatedVolume: 1200 },
  { phrase: 'cytotec delivery Egypt', category: 'purchase_delivery', categoryAr: 'تغطية ومتابعة مصر', estimatedVolume: 610 },
  { phrase: 'سايتوتك في مصر', category: 'purchase_delivery', categoryAr: 'تغطية ومتابعة مصر', estimatedVolume: 1300 },
  { phrase: 'شراء cytotec القاهرة', category: 'purchase_delivery', categoryAr: 'تغطية ومتابعة مصر', estimatedVolume: 840 },
  { phrase: 'cytotec حلوان', category: 'purchase_delivery', categoryAr: 'تغطية ومتابعة مصر', estimatedVolume: 670 },
  { phrase: 'حبوب الإجهاض في الجيزة', category: 'purchase_delivery', categoryAr: 'تغطية ومتابعة مصر', estimatedVolume: 890 },
  { phrase: 'cytotec Alexandria Egypt', category: 'purchase_delivery', categoryAr: 'تغطية ومتابعة مصر', estimatedVolume: 710 },
  { phrase: 'abortion pills Egypt discreet delivery', category: 'purchase_delivery', categoryAr: 'تغطية ومتابعة مصر', estimatedVolume: 530 },
  { phrase: 'شراء حبوب سايتوتك في مصر بسرية تامة', category: 'purchase_delivery', categoryAr: 'تغطية ومتابعة مصر', estimatedVolume: 940 },
  { phrase: 'سعر حبوب cytotec في الصيدليات المصرية', category: 'prices_pharmacies', categoryAr: 'تغطية ومتابعة مصر', estimatedVolume: 980 },
  { phrase: 'حبوب للاجهاض في مصر', category: 'purchase_delivery', categoryAr: 'تغطية ومتابعة مصر', estimatedVolume: 860 },
  { phrase: 'دواء للاجهاض في مصر', category: 'purchase_delivery', categoryAr: 'تغطية ومتابعة مصر', estimatedVolume: 820 },
  { phrase: 'ادويه الاجهاض في مصر', category: 'purchase_delivery', categoryAr: 'تغطية ومتابعة مصر', estimatedVolume: 890 },
  { phrase: 'حبوب اجهاض بمصر', category: 'purchase_delivery', categoryAr: 'تغطية ومتابعة مصر', estimatedVolume: 840 },
  { phrase: 'حبوب سايتوتك مصر', category: 'purchase_delivery', categoryAr: 'تغطية ومتابعة مصر', estimatedVolume: 980 },

  // 3. Medical Dosage, Instructions & Usage Keywords
  { phrase: 'طريقة استخدام حبوب سايتوتك للاجهاض', category: 'dosage_usage', categoryAr: 'بروتوكولات الاستخدام والجرعات', estimatedVolume: 960 },
  { phrase: 'استخدام حبوب سايتوتك', category: 'dosage_usage', categoryAr: 'بروتوكولات الاستخدام والجرعات', estimatedVolume: 810 },
  { phrase: 'طريقة استخدام cytotec للاجهاض', category: 'dosage_usage', categoryAr: 'بروتوكولات الاستخدام والجرعات', estimatedVolume: 920 },
  { phrase: 'استخدامات حبوب سايتوتك', category: 'dosage_usage', categoryAr: 'بروتوكولات الاستخدام والجرعات', estimatedVolume: 730 },
  { phrase: 'برشام سايتوتك للاجهاض', category: 'dosage_usage', categoryAr: 'بروتوكولات الاستخدام والجرعات', estimatedVolume: 890 },
  { phrase: 'برشام الاجهاض سايتوتك', category: 'dosage_usage', categoryAr: 'بروتوكولات الاستخدام والجرعات', estimatedVolume: 900 },
  { phrase: 'كيفية استخدام حبوب سايتوتك', category: 'dosage_usage', categoryAr: 'بروتوكولات الاستخدام والجرعات', estimatedVolume: 860 },
  { phrase: 'متى يبدأ مفعول cytotec', category: 'dosage_usage', categoryAr: 'بروتوكولات الاستخدام والجرعات', estimatedVolume: 810 },
  { phrase: 'طريقة استخدام cytotec للاجهاض في المنزل', category: 'dosage_usage', categoryAr: 'بروتوكولات الاستخدام والجرعات', estimatedVolume: 920 },
  { phrase: 'كيفية استخدام حبوب السايتوتك', category: 'dosage_usage', categoryAr: 'بروتوكولات الاستخدام والجرعات', estimatedVolume: 840 },
  { phrase: 'طريقة استخدام حبوب سايتوتك للاجهاض في الشهر الاول', category: 'dosage_usage', categoryAr: 'بروتوكولات الاستخدام والجرعات', estimatedVolume: 940 },
  { phrase: 'استعمال حبوب سايتوتك', category: 'dosage_usage', categoryAr: 'بروتوكولات الاستخدام والجرعات', estimatedVolume: 810 },
  { phrase: 'استخدام سايتوتك', category: 'dosage_usage', categoryAr: 'بروتوكولات الاستخدام والجرعات', estimatedVolume: 790 },
  { phrase: 'استخدام سايتوتك للاجهاض', category: 'dosage_usage', categoryAr: 'بروتوكولات الاستخدام والجرعات', estimatedVolume: 880 },
  { phrase: 'طريقة حبوب سايتوتك', category: 'dosage_usage', categoryAr: 'بروتوكولات الاستخدام والجرعات', estimatedVolume: 810 },

  // 4. Prices & Pharmaceutical Classifications
  { phrase: 'سعر حبوب سايتوتك', category: 'prices_pharmacies', categoryAr: 'الأسعار والتحقق الدوائي', estimatedVolume: 910 },
  { phrase: 'حبوب cytotec كم سعرها', category: 'prices_pharmacies', categoryAr: 'الأسعار والتحقق الدوائي', estimatedVolume: 780 },
  { phrase: 'سايتوتك صيدلية الدواء', category: 'prices_pharmacies', categoryAr: 'الأسعار والتحقق الدوائي', estimatedVolume: 830 },
  { phrase: 'سعر حبوب سيتوتيك في الرياض والدمام', category: 'prices_pharmacies', categoryAr: 'الأسعار والتحقق الدوائي', estimatedVolume: 890 },
  { phrase: 'cytotec سعر في الامارات', category: 'prices_pharmacies', categoryAr: 'الأسعار والتحقق الدوائي', estimatedVolume: 810 },
  { phrase: 'cytotec سعر في الإمارات', category: 'prices_pharmacies', categoryAr: 'الأسعار والتحقق الدوائي', estimatedVolume: 800 },
  { phrase: 'سعر حبوب سايتوتك للاجهاض', category: 'prices_pharmacies', categoryAr: 'الأسعار والتحقق الدوائي', estimatedVolume: 860 },
  { phrase: 'هل يمكن شراء سايتوتك بدون وصفة', category: 'prices_pharmacies', categoryAr: 'الأسعار والتحقق الدوائي', estimatedVolume: 790 },
  { phrase: 'موقع موثوق لشراء حبوب الإجهاض', category: 'purchase_delivery', categoryAr: 'الشراء والأصالة', estimatedVolume: 850 },

  // 5. Product Identification & Contrast
  { phrase: 'الفرق بين سايتوتك الاصلي والتقليد', category: 'general_medical', categoryAr: 'التحقق والموثوقية', estimatedVolume: 960 },
  { phrase: 'صور حبوب سايتوتك', category: 'general_medical', categoryAr: 'التحقق والموثوقية', estimatedVolume: 820 },
  { phrase: 'شكل حبوب سايتوتك', category: 'general_medical', categoryAr: 'التحقق والموثوقية', estimatedVolume: 790 },
  { phrase: 'برشام سايتوتك الاصلي', category: 'general_medical', categoryAr: 'التحقق والموثوقية', estimatedVolume: 870 },
  { phrase: 'شكل حبوب الاجهاض', category: 'general_medical', categoryAr: 'التحقق والموثوقية', estimatedVolume: 830 },
  { phrase: 'انواع حبوب سايتوتك', category: 'general_medical', categoryAr: 'التحقق والموثوقية', estimatedVolume: 810 },

  // 6. Side Effects, safety & Indications
  { phrase: 'الاثار الجانبيه لحبوب سايتوتك للاجهاض', category: 'side_effects', categoryAr: 'المضاعفات والإرشاد الصحي', estimatedVolume: 880 },
  { phrase: 'اعراض حبوب سايتوتك', category: 'side_effects', categoryAr: 'المضاعفات والإرشاد الصحي', estimatedVolume: 810 },
  { phrase: 'هل حبوب cytotec آمنة', category: 'side_effects', categoryAr: 'المضاعفات والإرشاد الصحي', estimatedVolume: 790 },
  { phrase: 'الاعراض الجانبية لدواء سايتوتك', category: 'side_effects', categoryAr: 'المضاعفات والإرشاد الصحي', estimatedVolume: 850 },
  { phrase: 'الاثار الجانبية لحبوب الاجهاض', category: 'side_effects', categoryAr: 'المضاعفات والإرشاد الصحي', estimatedVolume: 840 },
  { phrase: 'الاثار الجانبيه لحبوب الاجهاض', category: 'side_effects', categoryAr: 'المضاعفات والإرشاد الصحي', estimatedVolume: 830 },
  { phrase: 'اثار حبوب الاجهاض', category: 'side_effects', categoryAr: 'المضاعفات والإرشاد الصحي', estimatedVolume: 810 },
  { phrase: 'الأمراض والتحذيرات الطبية للميزوبروستول', category: 'side_effects', categoryAr: 'المضاعفات والإرشاد الصحي', estimatedVolume: 740 },

  // 7. Core Medical & Generics
  { phrase: 'حبوب الاجهاض', category: 'general_medical', categoryAr: 'العموم الطبي والعلوم', estimatedVolume: 2100 },
  { phrase: 'دواء الاجهاض', category: 'general_medical', categoryAr: 'العموم الطبي والعلوم', estimatedVolume: 1200 },
  { phrase: 'حبوب للاجهاض', category: 'general_medical', categoryAr: 'العموم الطبي والعلوم', estimatedVolume: 1300 },
  { phrase: 'ادوية الاجهاض', category: 'general_medical', categoryAr: 'العموم الطبي والعلوم', estimatedVolume: 980 },
  { phrase: 'ماهي حبوب سايتوتك', category: 'general_medical', categoryAr: 'العموم الطبي والعلوم', estimatedVolume: 890 },
  { phrase: 'سايتوتك 200', category: 'general_medical', categoryAr: 'البدائل الدوائية وعلم الأقراص', estimatedVolume: 1500 },
  { phrase: 'دواء سايتوتك', category: 'general_medical', categoryAr: 'البدائل الدوائية وعلم الأقراص', estimatedVolume: 1250 },
  { phrase: 'سايتوتك حبوب', category: 'general_medical', categoryAr: 'البدائل الدوائية وعلم الأقراص', estimatedVolume: 1100 },
  { phrase: 'ادوية للاجهاض', category: 'general_medical', categoryAr: 'العموم الطبي والعلوم', estimatedVolume: 940 },
  { phrase: 'سايتوتك للاجهاض', category: 'general_medical', categoryAr: 'العموم الطبي والعلوم', estimatedVolume: 1400 },
  { phrase: 'دواء اجهاض', category: 'general_medical', categoryAr: 'العموم الطبي والعلوم', estimatedVolume: 1150 },
  { phrase: 'انواع حبوب الاجهاض', category: 'general_medical', categoryAr: 'العموم الطبي والعلوم', estimatedVolume: 1205 },
  { phrase: 'دواء سايتوتك للاجهاض', category: 'general_medical', categoryAr: 'العموم الطبي والعلوم', estimatedVolume: 1530 },
  { phrase: 'افضل حبوب للاجهاض', category: 'general_medical', categoryAr: 'العموم الطبي والعلوم', estimatedVolume: 1120 },
  { phrase: 'اجهاض حبوب', category: 'general_medical', categoryAr: 'العموم الطبي والعلوم', estimatedVolume: 980 },
  { phrase: 'سايتوتك برشام', category: 'general_medical', categoryAr: 'البدائل الدوائية وعلم الأقراص', estimatedVolume: 890 },
  { phrase: 'دواء الاجهاض سايتوتك', category: 'general_medical', categoryAr: 'العموم الطبي والعلوم', estimatedVolume: 1100 },
  { phrase: 'تجارب حبوب سايتوتك للاجهاض', category: 'general_medical', categoryAr: 'العموم الطبي والعلوم', estimatedVolume: 1350 },
  { phrase: 'ماهي حبوب الاجهاض', category: 'general_medical', categoryAr: 'العموم الطبي والعلوم', estimatedVolume: 920 },
  { phrase: 'برشام سايتوتك', category: 'general_medical', categoryAr: 'البدائل الدوائية وعلم الأقراص', estimatedVolume: 1040 },
  { phrase: 'حبوب سايتوتك 200', category: 'general_medical', categoryAr: 'البدائل الدوائية وعلم الأقراص', estimatedVolume: 1190 },
  { phrase: 'اسم حبوب الاجهاض', category: 'general_medical', categoryAr: 'العموم الطبي والعلوم', estimatedVolume: 890 },
  { phrase: 'اقراص سايتوتك للاجهاض', category: 'general_medical', categoryAr: 'العموم الطبي والعلوم', estimatedVolume: 940 },
  { phrase: 'سايتوتك اجهاض', category: 'general_medical', categoryAr: 'العموم الطبي والعلوم', estimatedVolume: 1210 },
  { phrase: 'سعر حبوب سايتوتك', category: 'prices_pharmacies', categoryAr: 'الأسعار والتحقق الدوائي', estimatedVolume: 990 },
  { phrase: 'سايتوتك للإجهاض', category: 'general_medical', categoryAr: 'العموم الطبي والعلوم', estimatedVolume: 1230 },
  { phrase: 'cytotec برشام', category: 'general_medical', categoryAr: 'البدائل الدوائية وعلم الأقراص', estimatedVolume: 830 },
  { phrase: 'برشام اجهاض سايتوتك', category: 'general_medical', categoryAr: 'العموم الطبي والعلوم', estimatedVolume: 940 },
  { phrase: 'الإجهاض في الشهر الأول', category: 'general_medical', categoryAr: 'العموم الطبي والعلوم', estimatedVolume: 1410 },
  { phrase: 'حبوب تجهض', category: 'general_medical', categoryAr: 'العموم الطبي والعلوم', estimatedVolume: 900 },
  { phrase: 'علاج سايتوتك', category: 'general_medical', categoryAr: 'البدائل الدوائية وعلم الأقراص', estimatedVolume: 850 },
  { phrase: 'حبوب اجهاض فايزر', category: 'general_medical', categoryAr: 'البدائل الدوائية وعلم الأقراص', estimatedVolume: 990 },
  { phrase: 'ادوية للإجهاض', category: 'general_medical', categoryAr: 'العموم الطبي والعلوم', estimatedVolume: 940 },
  { phrase: 'برشام cytotec', category: 'general_medical', categoryAr: 'البدائل الدوائية وعلم الأقراص', estimatedVolume: 810 },
  { phrase: 'ادويه اجهاض الحمل', category: 'general_medical', categoryAr: 'العموم الطبي والعلوم', estimatedVolume: 1020 },
  { phrase: 'ادوية اجهاض', category: 'general_medical', categoryAr: 'العموم الطبي والعلوم', estimatedVolume: 1040 },
  { phrase: 'افضل حبوب اجهاض', category: 'general_medical', categoryAr: 'العموم الطبي والعلوم', estimatedVolume: 910 },
  { phrase: 'اسماء ادوية اجهاض', category: 'general_medical', categoryAr: 'العموم الطبي والعلوم', estimatedVolume: 900 },
  { phrase: 'سايتوتك فايزر', category: 'general_medical', categoryAr: 'البدائل الدوائية وعلم الأقراص', estimatedVolume: 1300 },
  { phrase: 'حبوب تساعد على الاجهاض', category: 'general_medical', categoryAr: 'العموم الطبي والعلوم', estimatedVolume: 890 },
  { phrase: 'انواع ادوية الاجهاض', category: 'general_medical', categoryAr: 'العموم الطبي والعلوم', estimatedVolume: 920 },
  { phrase: 'علاج سايتوتك للاجهاض', category: 'general_medical', categoryAr: 'العموم الطبي والعلوم', estimatedVolume: 1100 },
  { phrase: 'حبوب ستاتيك', category: 'general_medical', categoryAr: 'العموم الطبي والعلوم', estimatedVolume: 610 },
  { phrase: 'تجاربكم مع حبوب الاجهاض', category: 'general_medical', categoryAr: 'العموم الطبي والعلوم', estimatedVolume: 1200 },
  { phrase: 'ادوية الاجهاض في الشهر الاول', category: 'general_medical', categoryAr: 'العموم الطبي والعلوم', estimatedVolume: 1150 },
  { phrase: 'برشام للاجهاض', category: 'general_medical', categoryAr: 'العموم الطبي والعلوم', estimatedVolume: 980 },
  { phrase: 'أنواع حبوب الاجهاض', category: 'general_medical', categoryAr: 'العموم الطبي والعلوم', estimatedVolume: 940 },
  { phrase: 'سايتوتك والاجهاض', category: 'general_medical', categoryAr: 'العموم الطبي والعلوم', estimatedVolume: 1130 },
  { phrase: 'برشام للإجهاض', category: 'general_medical', categoryAr: 'العموم الطبي والعلوم', estimatedVolume: 890 },
  { phrase: 'تجارب حبوب الاجهاض', category: 'general_medical', categoryAr: 'العموم الطبي والعلوم', estimatedVolume: 1110 },
  { phrase: 'برشام اجهاض', category: 'general_medical', categoryAr: 'العموم الطبي والعلوم', estimatedVolume: 980 },
  { phrase: 'دواء للاجهاض الحمل', category: 'general_medical', categoryAr: 'العموم الطبي والعلوم', estimatedVolume: 870 },
  { phrase: 'انواع برشام للاجهاض', category: 'general_medical', categoryAr: 'العموم الطبي والعلوم', estimatedVolume: 830 },
  { phrase: 'الاجهاض في الشهر الاول', category: 'general_medical', categoryAr: 'العموم الطبي والعلوم', estimatedVolume: 1400 },
  { phrase: 'ادويه اسقاط الجنين', category: 'general_medical', categoryAr: 'العموم الطبي والعلوم', estimatedVolume: 910 },
  { phrase: 'معلومات عن الاجهاض', category: 'general_medical', categoryAr: 'العموم الطبي والعلوم', estimatedVolume: 850 },
  { phrase: 'سايتوتك بعد الإجهاض', category: 'general_medical', categoryAr: 'العموم الطبي والعلوم', estimatedVolume: 840 },
  { phrase: 'حبوب الشهر الاول من الحمل', category: 'general_medical', categoryAr: 'العموم الطبي والعلوم', estimatedVolume: 990 },
  { phrase: 'اقراص الإجهاض', category: 'general_medical', categoryAr: 'العموم الطبي والعلوم', estimatedVolume: 910 },
  { phrase: 'ماهي ادوية الاجهاض', category: 'general_medical', categoryAr: 'العموم الطبي والعلوم', estimatedVolume: 830 },
  { phrase: 'سايتوتك دواء', category: 'general_medical', categoryAr: 'العموم الطبي والعلوم', estimatedVolume: 940 },
  { phrase: 'برشام للاجهاض في الشهر الاول', category: 'general_medical', categoryAr: 'العموم الطبي والعلوم', estimatedVolume: 980 },
  { phrase: 'برشام cytotec استخدامه', category: 'general_medical', categoryAr: 'العموم الطبي والعلوم', estimatedVolume: 810 },
  { phrase: 'حبة الإجهاض', category: 'general_medical', categoryAr: 'العموم الطبي والعلوم', estimatedVolume: 1100 },
  { phrase: 'علاج الإجهاض في الشهر الأول', category: 'general_medical', categoryAr: 'العموم الطبي والعلوم', estimatedVolume: 1030 },
  { phrase: 'سايتوتك تجارب', category: 'general_medical', categoryAr: 'العموم الطبي والعلوم', estimatedVolume: 1220 },
  { phrase: 'دواء الإجهاض في الشهر الأول', category: 'general_medical', categoryAr: 'العموم الطبي والعلوم', estimatedVolume: 1120 },
  { phrase: 'افضل انواع حبوب الاجهاض', category: 'general_medical', categoryAr: 'العموم الطبي والعلوم', estimatedVolume: 960 },
  { phrase: 'اقوى حبوب للاجهاض', category: 'general_medical', categoryAr: 'العموم الطبي والعلوم', estimatedVolume: 1040 },
  { phrase: 'نوع حبوب للاجهاض', category: 'general_medical', categoryAr: 'العموم الطبي والعلوم', estimatedVolume: 810 },
  { phrase: 'برشام اجهاض الحمل', category: 'general_medical', categoryAr: 'العموم الطبي والعلوم', estimatedVolume: 910 },
  { phrase: 'ابي حبوب اجهاض', category: 'general_medical', categoryAr: 'العموم الطبي والعلوم', estimatedVolume: 850 },
  { phrase: 'علاج الاجهاض', category: 'general_medical', categoryAr: 'العموم الطبي والعلوم', estimatedVolume: 880 },
  { phrase: 'سايتوتك في الشهر الاول', category: 'general_medical', categoryAr: 'العموم الطبي والعلوم', estimatedVolume: 1210 },
  { phrase: 'برشام الاجهاض', category: 'general_medical', categoryAr: 'العموم الطبي والعلوم', estimatedVolume: 1100 },
  { phrase: 'أدوية تساعد على الإجهاض', category: 'general_medical', categoryAr: 'العموم الطبي والعلوم', estimatedVolume: 940 },
  { phrase: 'رقم حبوب اجهاض', category: 'general_medical', categoryAr: 'العموم الطبي والعلوم', estimatedVolume: 830 },
  { phrase: 'اجهاض الحمل في الشهر الاول', category: 'general_medical', categoryAr: 'العموم الطبي والعلوم', estimatedVolume: 1320 },
  { phrase: 'ادوية اسقاط الحمل', category: 'general_medical', categoryAr: 'العموم الطبي والعلوم', estimatedVolume: 980 },
  { phrase: 'كبسولات الاجهاض', category: 'general_medical', categoryAr: 'العموم الطبي والعلوم', estimatedVolume: 890 },
  { phrase: 'دواء اجهاض الحمل', category: 'general_medical', categoryAr: 'العموم الطبي والعلوم', estimatedVolume: 1010 },
  { phrase: 'دواء لإجهاض الجنين', category: 'general_medical', categoryAr: 'العموم الطبي والعلوم', estimatedVolume: 920 },
  { phrase: 'ماهو دواء سايتوتك', category: 'general_medical', categoryAr: 'العموم الطبي والعلوم', estimatedVolume: 850 },
  { phrase: 'السايتوتك اقراص', category: 'general_medical', categoryAr: 'البدائل الدوائية وعلم الأقراص', estimatedVolume: 910 },
  { phrase: 'الإجهاض بالحبوب', category: 'general_medical', categoryAr: 'العموم الطبي والعلوم', estimatedVolume: 1250 },
  { phrase: 'سايتوتك علاج', category: 'general_medical', categoryAr: 'العموم الطبي والعلوم', estimatedVolume: 940 },
  { phrase: 'اجهاض الشهر الاول', category: 'general_medical', categoryAr: 'العموم الطبي والعلوم', estimatedVolume: 1290 },
  { phrase: 'معلومات الحمل', category: 'general_medical', categoryAr: 'العموم الطبي والعلوم', estimatedVolume: 610 },
  { phrase: 'نوع برشام اجهاض', category: 'general_medical', categoryAr: 'العموم الطبي والعلوم', estimatedVolume: 740 },
  { phrase: 'الاجهاض في الشهر الاول من الحمل', category: 'general_medical', categoryAr: 'العموم الطبي والعلوم', estimatedVolume: 1380 },
  { phrase: 'تجاري سايتوتك', category: 'general_medical', categoryAr: 'العموم الطبي والعلوم', estimatedVolume: 810 },
  { phrase: 'الاجهاض فى الشهر الاول', category: 'general_medical', categoryAr: 'العموم الطبي والعلوم', estimatedVolume: 1290 },
  { phrase: 'الاجهاض من الشهر الاول', category: 'general_medical', categoryAr: 'العموم الطبي والعلوم', estimatedVolume: 1100 },
  { phrase: 'دواء اجهاض حمل', category: 'general_medical', categoryAr: 'العموم الطبي والعلوم', estimatedVolume: 940 },
  { phrase: 'اقراص اجهاض الحمل', category: 'general_medical', categoryAr: 'العموم الطبي والعلوم', estimatedVolume: 980 },
  { phrase: 'حبوب فترة الحمل', category: 'general_medical', categoryAr: 'العموم الطبي والعلوم', estimatedVolume: 710 },
  { phrase: 'الحمل بعد شهر من الاجهاض', category: 'general_medical', categoryAr: 'العموم الطبي والعلوم', estimatedVolume: 890 },
  { phrase: 'اجهاض بالحبوب', category: 'general_medical', categoryAr: 'العموم الطبي والعلوم', estimatedVolume: 1250 },
  { phrase: 'دواء يستخدم للاجهاض', category: 'general_medical', categoryAr: 'العموم الطبي والعلوم', estimatedVolume: 1130 },
  { phrase: 'الاثار الجانبية للاجهاض', category: 'general_medical', categoryAr: 'العموم الطبي والعلوم', estimatedVolume: 890 },
  { phrase: 'افضل دواء للاجهاض', category: 'general_medical', categoryAr: 'العموم الطبي والعلوم', estimatedVolume: 1040 },
  { phrase: 'اقوى حبوب اجهاض', category: 'general_medical', categoryAr: 'العموم الطبي والعلوم', estimatedVolume: 1090 },
  { phrase: 'فترة الحمل', category: 'general_medical', categoryAr: 'العموم الطبي والعلوم', estimatedVolume: 610 },
  { phrase: 'علاج يساعد على الاجهاض', category: 'general_medical', categoryAr: 'العموم الطبي والعلوم', estimatedVolume: 910 },
  { phrase: 'اجهاض الحمل', category: 'general_medical', categoryAr: 'العموم الطبي والعلوم', estimatedVolume: 1290 },
  { phrase: 'ادويه اجهاض الجنين', category: 'general_medical', categoryAr: 'العموم الطبي والعلوم', estimatedVolume: 910 },
  { phrase: 'الادوية التي تساعد على الاجهاض', category: 'general_medical', categoryAr: 'العموم الطبي والعلوم', estimatedVolume: 1100 },
  { phrase: 'في الشهر الاول', category: 'general_medical', categoryAr: 'العموم الطبي والعلوم', estimatedVolume: 940 },
  { phrase: 'افضل برشام للاجهاض', category: 'general_medical', categoryAr: 'العموم الطبي والعلوم', estimatedVolume: 1010 },
  { phrase: 'برشام يساعد ع الاجهاض', category: 'general_medical', categoryAr: 'العموم الطبي والعلوم', estimatedVolume: 940 },
  { phrase: 'حبوب الاجهاض وانواعها', category: 'general_medical', categoryAr: 'العموم الطبي والعلوم', estimatedVolume: 1180 },
  { phrase: 'علاج للاجهاض', category: 'general_medical', categoryAr: 'العموم الطبي والعلوم', estimatedVolume: 890 },
  { phrase: 'ادوية اجهاض الجنين', category: 'general_medical', categoryAr: 'العموم الطبي والعلوم', estimatedVolume: 910 },
  { phrase: 'دواء فعال للاجهاض', category: 'general_medical', categoryAr: 'العموم الطبي والعلوم', estimatedVolume: 1030 },
  { phrase: 'حبوب بداية الحمل', category: 'general_medical', categoryAr: 'العموم الطبي والعلوم', estimatedVolume: 810 },
  { phrase: 'اسماء ادويه الاجهاض', category: 'general_medical', categoryAr: 'العموم الطبي والعلوم', estimatedVolume: 920 },
  { phrase: 'ماهو علاج سايتوتك', category: 'general_medical', categoryAr: 'العموم الطبي والعلوم', estimatedVolume: 810 },
  { phrase: 'cytotec استخدام', category: 'general_medical', categoryAr: 'البدائل الدوائية وعلم الأقراص', estimatedVolume: 930 },
  { phrase: 'cytotec استخداماته', category: 'general_medical', categoryAr: 'البدائل الدوائية وعلم الأقراص', estimatedVolume: 890 },
  { phrase: 'cytotec ماهو دواء', category: 'general_medical', categoryAr: 'العموم الطبي والعلوم', estimatedVolume: 855 },
  { phrase: 'كيفيه الإجهاض', category: 'general_medical', categoryAr: 'العموم الطبي والعلوم', estimatedVolume: 820 },
];
